name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  install-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Read Python Version
      id: get_python_version
      run: |
        PYTHON_VERSION=$(cat python_version.txt)
        echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_ENV
        echo "PYTHON_VERSION is $PYTHON_VERSION"
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    
    - name: Lint
      run: flake8 models tests
    
    - name: Run Tests
      run: pytest tests/TestBasic.py
